# Site settings
title: Michał Lach | UI Developer
email: kontakt@michal-lach.pl
description: > # this means to ignore newlines until "baseurl:"
  HTML5, CSS3 & Angular.js engineer from Poland, Gdynia.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://michal-lach.pl" # the base hostname & protocol for your site
twitter_username: padsbanger
github_username:  padsbanger

# Build settings
markdown: kramdown
exclude: ['README.md', 'node_modules', 'package.json', 'Gruntfile.js']
permalink: /projects/:title
paginate: 6
paginate_path: "/projects/:num/"